// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/18/2025, 1:15:21 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/bold/Downloads/Egshin Artger (1)/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bold/Downloads/Egshin Artger (1)/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bold/Downloads/Egshin Artger (1)/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bold/Downloads/Egshin Artger (1)/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bold/Downloads/Egshin Artger (1)/plugins/**/*.{js,ts,mjs}","/Users/bold/Downloads/Egshin Artger (1)/composables/**/*.{js,ts,mjs}","/Users/bold/Downloads/Egshin Artger (1)/utils/**/*.{js,ts,mjs}","/Users/bold/Downloads/Egshin Artger (1)/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bold/Downloads/Egshin Artger (1)/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/bold/Downloads/Egshin Artger (1)/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/bold/Downloads/Egshin Artger (1)/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;